default: &default
  adapter: sqlite3

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: mysql2
  url: <%=  ENV['DATABASE_URL'] %>
  encoding: utf8
  pool: 5

uat:
  adapter: mysql2
  url: <%=  ENV['DATABASE_URL'] %>
  encoding: utf8
  pool: 5
